"""empty message

Revision ID: 09c31fbc4b0f
Revises: 
Create Date: 2022-03-05 15:21:46.692279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c31fbc4b0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('loaction', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('regist_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'regist_date')
    op.drop_column('users', 'loaction')
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
