"""empty message

Revision ID: 59db03a32e67
Revises: 7d74978c6a4b
Create Date: 2022-03-10 10:37:43.999629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59db03a32e67'
down_revision = '7d74978c6a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Blog_Categorys', sa.Column('remark', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Blog_Categorys', 'remark')
    # ### end Alembic commands ###
