"""empty message

Revision ID: 7d74978c6a4b
Revises: 09c31fbc4b0f
Create Date: 2022-03-05 17:09:08.142269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d74978c6a4b'
down_revision = '09c31fbc4b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.String(length=20), nullable=True))
    op.drop_column('users', 'loaction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('loaction', sa.VARCHAR(length=20), nullable=True))
    op.drop_column('users', 'location')
    # ### end Alembic commands ###
