"""empty message

Revision ID: a20ebda4a551
Revises: e4af45c08d74
Create Date: 2022-03-15 15:28:24.086260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a20ebda4a551'
down_revision = 'e4af45c08d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Blog_Main', sa.Column('blog_cover_url', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Blog_Main', 'blog_cover_url')
    # ### end Alembic commands ###
