"""empty message

Revision ID: e4af45c08d74
Revises: 59db03a32e67
Create Date: 2022-03-10 16:49:51.587229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4af45c08d74'
down_revision = '59db03a32e67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BlogMains')
    op.drop_constraint(None, 'Blog_Posts', type_='foreignkey')
    op.create_foreign_key(None, 'Blog_Posts', 'Blog_Main', ['blog_main_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Blog_Posts', type_='foreignkey')
    op.create_foreign_key(None, 'Blog_Posts', 'BlogMains', ['blog_main_id'], ['id'])
    op.create_table('BlogMains',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('blog_name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('blog_descri', sa.VARCHAR(length=200), nullable=True),
    sa.Column('blog_create_date', sa.DATETIME(), nullable=True),
    sa.Column('artist', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['artist'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
